@startuml 

interface Запрос {
    +Заголовок
    +Данные
    +ID
}

interface Сегмент {
    +Данные
    +Индекс
    +ID запроса
}

Запрос o-- Сегмент

class Клиент {
    +Хост:Порт
    +Пост()
}


class Коцнентратор {
    +Порт
    +Слушать()
    #Сохранить(Запрос)
}


class Отстойник {
    -Сегменты: Сегмент[1..*]
    +Сохранить(Запрос)
    #Разделать(Запрос)
    +ВыдатьСегмент()
    -Самоочистка()
}

class Диспенсер {
    +Хост:Порт
    +Пост()
    #ВзятьСегмент()
    #ОтправитьСегмент()
}

interface Стекер {
    +Порт
    +Слушать()
    #ПолучитьСегмент()
    #Сохранить(Сегмент)
}

interface Склад {
    -Сегменты: Сегмент[1..*]
    +Уложить(Сегмент)
    #ВосстановитьЗапрос()
}

interface Шаттл {
    +Хост:Порт
    +Пост()
    #ВзятьЗпрос()
    #ОтправитьЗапрос()
}

interface Сервер {
    +Порт
    +Слушать()
}

Клиент ..> Коцнентратор : Переправка запроса

Коцнентратор ..> Отстойник : Сброс запроса

Диспенсер ..> Отстойник : Выемка Сегмента

Диспенсер ..> Стекер : Отправка Сегмента

Стекер ..> Склад : Укладка Сегмента

Шаттл ..> Склад : Восстановление запроса

Шаттл ..> Сервер : Отправка запроса

@enduml